### ISSUE TITLE
Some gamepad icons off center

### ISSUE THREAD

**Issue by JamesCoyle** [chteuchteu/MaterialDesignIcons-Picker#28]
Not sure if this is on our end or yours. 

![image](https://user-images.githubusercontent.com/10384436/57611161-22107d80-756a-11e9-9cd0-c7f515b4b7e5.png)

**Comment by chteuchteu** [comment]
Thanks for the bug report! Note: this extension uses the webfont to show the icons in the list

Icon's container is properly aligned:

![Screenshot from 2019-05-13 11-32-03](https://user-images.githubusercontent.com/1551971/57611343-f3e36b80-7572-11e9-8e16-f63d6105e678.png)

`::before` selector seems weird though: it has a 0px width:
![Screenshot from 2019-05-13 11-32-18](https://user-images.githubusercontent.com/1551971/57611393-0d84b300-7573-11e9-91ea-78326a4181f2.png)

Other icons (non-misaligned ones) have a 24px width:
![Screenshot from 2019-05-13 11-32-15](https://user-images.githubusercontent.com/1551971/57611411-183f4800-7573-11e9-8c74-d63187b9346e.png)

Could it be an issue with the webfont?

**Comment by Templarian** [comment]
That is really weird. I fixed this bug in 3.6.95 and the CDN appears to be showing it as fixed.

Maybe those codepoints don't play nice in the plugin or it's how it's being rendered.

**Comment by chteuchteu** [comment]
Weird indeed! I tried to force a refresh of all the assets on my local dev environment, it didn't fix this issue.
I'm using an embedded (unmodified) version of `materialdesignicons-webfont.woff2` in the extension

Here's the icons styling: [style.scss](https://github.com/chteuchteu/MaterialDesignIcons-Picker/blob/master/src/css/style.scss#L239). Do you see anything to could trigger this issue?

**Comment by JamesCoyle** [comment]
This seems to be fixed in the current version.

**Comment by chteuchteu** [comment]
Nice to know, thanks for the feedback!
